CREATE TABLE IF NOT EXISTS public.responsabilidades_catalogo (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  responsabilidade TEXT NOT NULL,
  area TEXT NOT NULL,
  nivel TEXT NOT NULL DEFAULT 'todos'
    CHECK (nivel IN ('jr', 'pl', 'sr', 'coordenacao', 'especialista', 'c_level', 'todos')),
  ativo BOOLEAN DEFAULT true,
  criado_por TEXT DEFAULT 'sistema',
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(responsabilidade, area, nivel)
);

ALTER TABLE public.responsabilidades_catalogo ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated can read responsabilidades_catalogo"
ON public.responsabilidades_catalogo FOR SELECT TO authenticated USING (true);

CREATE POLICY "Staff can manage responsabilidades_catalogo"
ON public.responsabilidades_catalogo FOR INSERT TO authenticated
WITH CHECK (
  public.has_role(auth.uid(), 'super_admin') OR
  public.has_role(auth.uid(), 'admin_rh') OR
  public.has_role(auth.uid(), 'gestor_rh') OR
  public.has_role(auth.uid(), 'recrutador')
);

INSERT INTO public.responsabilidades_catalogo (responsabilidade, area, nivel) VALUES
('Executar peças gráficas para redes sociais seguindo briefing e manual de marca', 'Design', 'jr'),
('Apoiar na produção de materiais de ponto de venda e embalagens', 'Design', 'jr'),
('Organizar e manter atualizado o banco de assets e arquivos de design', 'Design', 'jr'),
('Realizar ajustes e revisões em layouts a partir de feedbacks', 'Design', 'jr'),
('Apoiar na preparação de arquivos para impressão e produção', 'Design', 'jr'),
('Criar e desenvolver peças gráficas para campanhas, embalagens e materiais de ponto de venda', 'Design', 'pl'),
('Garantir a consistência da identidade visual em todos os pontos de contato da marca', 'Design', 'pl'),
('Desenvolver e manter o guia de estilo e manual de marca atualizado', 'Design', 'pl'),
('Colaborar com marketing e produto na criação de novos materiais e lançamentos', 'Design', 'pl'),
('Preparar arquivos técnicos para fornecedores e gráficas', 'Design', 'pl'),
('Apresentar e defender decisões de design para stakeholders internos', 'Design', 'pl'),
('Liderar a estratégia visual da marca, garantindo coerência entre todos os canais', 'Design', 'sr'),
('Orientar e revisar o trabalho de designers juniores e plenos', 'Design', 'sr'),
('Conduzir projetos de identidade visual, design de produto e embalagem do briefing à entrega', 'Design', 'sr'),
('Avaliar e selecionar fornecedores de produção gráfica e impressão', 'Design', 'sr'),
('Desenvolver diretrizes criativas para novas linhas de produto', 'Design', 'sr'),
('Coordenar a equipe de design, distribuindo demandas e garantindo qualidade das entregas', 'Design', 'coordenacao'),
('Definir processos e ferramentas do fluxo de trabalho criativo', 'Design', 'coordenacao'),
('Alinhar a estratégia visual com as metas comerciais e de marketing', 'Design', 'coordenacao'),
('Gerenciar prazos, prioridades e capacidade da equipe', 'Design', 'coordenacao'),
('Criar e agendar conteúdo para redes sociais seguindo o calendário editorial', 'Marketing', 'jr'),
('Apoiar na produção de textos, legendas e copies para diferentes canais', 'Marketing', 'jr'),
('Monitorar e reportar métricas básicas de redes sociais e campanhas', 'Marketing', 'jr'),
('Pesquisar tendências, concorrentes e referências para alimentar o planejamento', 'Marketing', 'jr'),
('Planejar e executar campanhas de marketing digital (tráfego pago, email, social)', 'Marketing', 'pl'),
('Produzir e revisar conteúdos para blog, redes sociais e materiais de venda', 'Marketing', 'pl'),
('Analisar dados de performance e propor otimizações com base em métricas', 'Marketing', 'pl'),
('Gerenciar ferramentas de automação de marketing e CRM', 'Marketing', 'pl'),
('Coordenar ações com agências, freelancers e fornecedores externos', 'Marketing', 'pl'),
('Desenvolver e executar a estratégia de marketing integrado da marca', 'Marketing', 'sr'),
('Liderar campanhas de lançamento de produtos e ativações de marca', 'Marketing', 'sr'),
('Analisar dados de mercado, concorrência e comportamento do consumidor', 'Marketing', 'sr'),
('Definir e acompanhar KPIs de marketing alinhados às metas do negócio', 'Marketing', 'sr'),
('Coordenar equipe de marketing e garantir execução do planejamento anual', 'Marketing', 'coordenacao'),
('Alinhar estratégia de comunicação com as áreas de produto, comercial e design', 'Marketing', 'coordenacao'),
('Definir calendário editorial e campanhas sazonais', 'Marketing', 'coordenacao'),
('Prospectar novos clientes e lojistas via ligação, email e visitas', 'Comercial', 'jr'),
('Apoiar na apresentação e demonstração de produtos para clientes', 'Comercial', 'jr'),
('Registrar e atualizar informações de leads e oportunidades no CRM', 'Comercial', 'jr'),
('Acompanhar pedidos, prazo de entrega e pós-venda de clientes da carteira', 'Comercial', 'jr'),
('Gerenciar carteira de clientes e garantir atingimento das metas de venda', 'Comercial', 'pl'),
('Conduzir negociações comerciais com lojistas e distribuidores', 'Comercial', 'pl'),
('Apresentar portfólio de produtos, condições e novidades para clientes', 'Comercial', 'pl'),
('Analisar dados de sell-in e sell-out para identificar oportunidades', 'Comercial', 'pl'),
('Desenvolver e executar estratégia de expansão de canais e mercados', 'Comercial', 'sr'),
('Gerenciar contas-chave (key accounts) e negociações estratégicas', 'Comercial', 'sr'),
('Definir política comercial, tabelas de preços e condições de pagamento', 'Comercial', 'sr'),
('Gerenciar portfólio de grandes contas e garantir fidelização', 'Comercial', 'especialista'),
('Desenvolver planos de negócio e estratégias de crescimento por conta', 'Comercial', 'especialista'),
('Conduzir negociações complexas com autonomia e profundidade', 'Comercial', 'especialista'),
('Apoiar no processo seletivo: triagem de currículos, agendamento e entrevistas iniciais', 'RH', 'jr'),
('Realizar onboarding de novos colaboradores e garantir entrega de equipamentos e acessos', 'RH', 'jr'),
('Manter atualizada a documentação de colaboradores CLT e PJ no sistema', 'RH', 'jr'),
('Apoiar nos processos de DP: controle de ponto, férias e documentos admissionais', 'RH', 'jr'),
('Conduzir processos seletivos completos, da abertura ao fechamento da vaga', 'RH', 'pl'),
('Gerenciar onboarding, offboarding e movimentações de colaboradores', 'RH', 'pl'),
('Apoiar gestores na aplicação de feedbacks e avaliações de desempenho', 'RH', 'pl'),
('Administrar benefícios, folha de pagamento e contratos CLT e PJ', 'RH', 'pl'),
('Garantir conformidade com a legislação trabalhista e eSocial', 'RH', 'pl'),
('Desenvolver e implementar políticas de RH alinhadas à cultura da empresa', 'RH', 'sr'),
('Atuar como business partner para as áreas, orientando líderes em decisões de pessoas', 'RH', 'sr'),
('Liderar ciclos de avaliação de desempenho e calibração', 'RH', 'sr'),
('Desenvolver programas de engajamento, cultura e retenção de talentos', 'RH', 'sr'),
('Realizar recebimento, conferência e armazenagem de mercadorias', 'Logística', 'jr'),
('Controlar entradas e saídas de estoque no sistema', 'Logística', 'jr'),
('Apoiar na separação e expedição de pedidos', 'Logística', 'jr'),
('Manter a organização e o inventário do armazém', 'Logística', 'jr'),
('Gerenciar processos de recebimento, armazenagem, separação e expedição', 'Logística', 'pl'),
('Controlar estoque e garantir acuracidade dos inventários', 'Logística', 'pl'),
('Acompanhar indicadores logísticos e propor melhorias de processo', 'Logística', 'pl'),
('Apoiar processos de importação: documentação, Incoterms e desembaraço', 'Logística', 'pl'),
('Desenvolver e otimizar processos logísticos de armazenagem e distribuição', 'Logística', 'sr'),
('Gerenciar indicadores de performance (OTD, fill rate, acuracidade)', 'Logística', 'sr'),
('Conduzir projetos de melhoria operacional e redução de custos logísticos', 'Logística', 'sr'),
('Coordenar a equipe e as operações do armazém e distribuição', 'Logística', 'coordenacao'),
('Garantir cumprimento de prazos, qualidade e segurança na operação', 'Logística', 'coordenacao'),
('Gerenciar SLAs com transportadoras e parceiros logísticos', 'Logística', 'coordenacao'),
('Desenvolver e manter sistemas e aplicações web conforme especificações técnicas', 'TI', 'pl'),
('Implementar funcionalidades, correções e melhorias nos sistemas internos', 'TI', 'pl'),
('Garantir a qualidade do código por meio de testes e revisões', 'TI', 'pl'),
('Documentar arquitetura, decisões técnicas e processos de desenvolvimento', 'TI', 'pl'),
('Colaborar com produto e negócio para traduzir requisitos em soluções técnicas', 'TI', 'pl'),
('Liderar o desenvolvimento técnico de projetos e sistemas críticos', 'TI', 'sr'),
('Definir arquitetura de software, padrões e boas práticas da equipe', 'TI', 'sr'),
('Revisar código e orientar desenvolvedores juniores e plenos', 'TI', 'sr'),
('Garantir segurança, escalabilidade e disponibilidade dos sistemas', 'TI', 'sr'),
('Operar máquinas e equipamentos de produção conforme procedimentos técnicos', 'Operacional', 'jr'),
('Realizar controle de qualidade durante o processo produtivo', 'Operacional', 'jr'),
('Registrar dados de produção e comunicar ocorrências ao supervisor', 'Operacional', 'jr'),
('Seguir rigorosamente as normas de segurança e EPIs obrigatórios', 'Operacional', 'jr'),
('Controlar e acompanhar indicadores de produção (volume, qualidade, rejeito)', 'Operacional', 'pl'),
('Garantir o cumprimento do plano de produção diário e semanal', 'Operacional', 'pl'),
('Identificar e reportar não conformidades e oportunidades de melhoria', 'Operacional', 'pl'),
('Supervisionar a operação e garantir o cumprimento das metas de produção', 'Operacional', 'especialista'),
('Liderar equipe operacional e desenvolver talentos do chão de fábrica', 'Operacional', 'especialista'),
('Garantir conformidade com NRs, laudos técnicos e requisitos regulatórios', 'Operacional', 'especialista'),
('Realizar lançamentos de contas a pagar e a receber no sistema', 'Financeiro', 'jr'),
('Efetuar conciliação bancária e conferência de extratos', 'Financeiro', 'jr'),
('Apoiar na organização e arquivo de documentos fiscais e contábeis', 'Financeiro', 'jr'),
('Emitir notas fiscais e boletos conforme solicitação', 'Financeiro', 'jr'),
('Controlar e acompanhar o fluxo de caixa diário e projeções de curto prazo', 'Financeiro', 'pl'),
('Elaborar relatórios financeiros periódicos (DRE, fluxo de caixa, aging)', 'Financeiro', 'pl'),
('Garantir conformidade fiscal e tributária nas operações da empresa', 'Financeiro', 'pl'),
('Apoiar no fechamento contábil mensal e na interface com a contabilidade', 'Financeiro', 'pl'),
('Desenvolver e acompanhar o planejamento orçamentário e financeiro da empresa', 'Financeiro', 'sr'),
('Conduzir análises de viabilidade e retorno de investimentos', 'Financeiro', 'sr'),
('Apoiar a diretoria em decisões estratégicas com base em dados financeiros', 'Financeiro', 'sr'),
('Apoiar no levantamento e documentação de requisitos de produto', 'Produto', 'jr'),
('Conduzir pesquisas com usuários e compilar insights para a equipe', 'Produto', 'jr'),
('Auxiliar na priorização e refinamento do backlog com o time de desenvolvimento', 'Produto', 'jr'),
('Criar e manter documentação de produto (user stories, fluxos, wireframes)', 'Produto', 'jr'),
('Descobrir, priorizar e especificar funcionalidades com base em dados e pesquisa', 'Produto', 'pl'),
('Gerenciar o backlog e garantir alinhamento entre negócio e time técnico', 'Produto', 'pl'),
('Conduzir cerimônias ágeis e garantir a cadência de entregas', 'Produto', 'pl'),
('Analisar métricas de produto e propor experimentos de melhoria', 'Produto', 'pl'),
('Definir a visão e estratégia do produto alinhada às metas do negócio', 'Produto', 'sr'),
('Liderar discovery, priorização e entrega de iniciativas estratégicas', 'Produto', 'sr'),
('Influenciar decisões de negócio com base em dados, métricas e pesquisa', 'Produto', 'sr'),
('Mentorar PMs e colaborar na estruturação da área de produto', 'Produto', 'sr')
ON CONFLICT (responsabilidade, area, nivel) DO NOTHING;