
ALTER TABLE public.candidatos
ADD COLUMN IF NOT EXISTS experiencias JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS formacoes JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS skills_candidato JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS sistemas_candidato JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS mensagem TEXT,
ADD COLUMN IF NOT EXISTS score_total NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS score_detalhado JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS score_calculado_em TIMESTAMPTZ;
